#!/bin/bash
#set -e
# Automatic Image file resizer
# Written by SirLagz
# Fixed 2016.04.17 by @ChrisPrimeish 

if [[ ! $(whoami) =~ "root" ]]; then
echo ""
echo "**********************************"
echo "*** This should be run as root ***"
echo "**********************************"
echo ""
exit
fi

if [[ -z $1 ]]; then
echo "Usage: $0 <block_device>"
exit
fi

if [[ ! -e $1 || ! $(file $1) != "*block device*" ]]; then
echo "Error : $1 is not a block device, or device does not exist"
exit
fi

blockdev=$1
partinfo=`parted -m $blockdev unit B print`

echo "Partition info for $blockdev:"
echo "$partinfo"
partnumber=`echo "$partinfo" | grep ext4 | awk -F: ' { print $1 } '`
echo "ext4 partition found, partition number is $partnumber"
blockdevpart="$blockdev$partnumber"
echo "ext4 partition blockdev device constructed: $blockdevpart"
partstart=`echo "$partinfo" | grep ext4 | awk -F: ' { print substr($2,0,length($2)) } '`
echo "ext4 partition starts at offset $partstart"

echo "Press enter to continue if you have valid data above..."
read

echo "This next step might complain about superblock or partition table corruption, answer N to the abort prompt if it comes up:"
e2fsck -f $blockdevpart

minsize=`resize2fs -P $blockdevpart | awk -F': ' ' { print $2 } '`
echo "Minimum size of ext4 partition determined to be $minsize"

# Modified minsize calc by Kevin Rattai
#
# original minsize produces 0bytes on partition, calculated as:
# minsize=`echo "$minsize+1000" | bc`
#
# New minsize calc produces 10% minsize as available space
minsize=`echo "($minsize+($minsize*0.1))/1" | bc`
echo "Adding 10 percent to minimum size to leave a little breathing room, now is $minsize.  Resizing filesystem after you press enter to continue..."

read

resize2fs -p $blockdevpart $minsize
e2fsck -fy $blockdevpart
echo "Resizing ext4 filesystem on $blockdevpart to $minsize complete!"
sleep 1
partnewsize=`echo "$minsize * 4096" | bc`
echo "Partition new size $partnewsize"
newpartend=`echo "$partstart + $partnewsize" | bc`
echo "New partition end offset $newpartend... removing original ext4 partition table entry..."
parted --script "$blockdev" rm $partnumber
echo "Creating new shrunken ext4 partition table entry..."
parted --script "$blockdev" unit B mkpart primary $partstart $newpartend

echo "Done!"

